spring:
  application: 
    name: liquibase-demo
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console